### PR TITLE
Add check-list for eCommerce-Application Sprint 2 xCheck

### PR DESCRIPTION
**Pull request by EternalRival**
chrome_42f1b99dff

### CODE REVIEW

**Comment by EternalRival** [comment]
@valerydluski

**Comment by valerydluski** [comment]
@EternalRival can you resolve conflicts?

**Comment by EternalRival** [comment]
> @EternalRival can you resolve conflicts?

maybe in an hour or two

**Comment by EternalRival** [comment]
> @EternalRival can you resolve conflicts?

done

**Review by valerydluski — APPROVED** [review]

**Pull request merged**
